export default function Dashboard() {
  return (
    <div className="Dashboard" style={{ margin: "2rem" }}>
      <h1>React App</h1>

      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus fugiat doloribus voluptatum sunt laborum neque optio quam illum reprehenderit dolores consequuntur dolore inventore quis, at nostrum dolor excepturi accusamus adipisci id laboriosam nam facere? Dolores sint quae ipsa fugiat ab quod sed voluptatum repellendus amet rerum dolorum quidem perferendis atque animi eius eligendi, enim doloremque exercitationem voluptatem ex quasi? Excepturi possimus, omnis repudiandae alias dolores tempore voluptates quasi dignissimos sunt odio quia ea nostrum ad at voluptatem perspiciatis esse impedit unde officia eum laudantium. Ullam animi optio cupiditate laudantium saepe? Ducimus tempora a ut nihil. Voluptates, molestias provident? Corporis et ea provident quo expedita illo, aut magni neque. Reprehenderit harum ducimus sed beatae error recusandae odit enim quis dolores labore.</p>
      <p>Necessitatibus, cupiditate maxime. Aliquam eos ipsa aut esse expedita nulla impedit laboriosam vel autem repellat. Libero beatae labore facilis animi, totam recusandae voluptatum quod enim fugiat pariatur. Ratione suscipit vitae saepe modi similique impedit quidem velit fuga cumque sunt enim earum maiores itaque corrupti sequi ex, ducimus nisi! Hic praesentium ab blanditiis beatae libero eius ipsam nisi laboriosam ducimus. Fugiat, explicabo accusamus neque ipsum assumenda sed voluptatum suscipit quas odio omnis alias temporibus molestias, veniam possimus distinctio nisi cum necessitatibus quia veritatis repellat. Totam odio aliquam mollitia nostrum odit velit accusamus! Natus voluptatum illo, explicabo id fugit voluptatibus beatae aut recusandae. Cumque temporibus, omnis in ea eos aliquid! Beatae nulla ad, aperiam molestiae deleniti ducimus fuga consequuntur temporibus impedit porro.</p>
      <p>Error ea laborum, autem provident labore sunt impedit neque. Quo facere quos esse incidunt fuga, aut autem inventore, voluptatem nisi corrupti commodi ipsum temporibus sed, asperiores ab eligendi adipisci molestiae ullam impedit quia repellat magnam reprehenderit architecto labore. Dolorum delectus veritatis ipsum tempore corporis consectetur sit aperiam est nisi porro quisquam, doloribus dignissimos quasi, sequi voluptas nesciunt ut voluptates? Libero commodi dignissimos dolores iusto, ut obcaecati voluptatum nisi quod quo harum sapiente at perspiciatis dicta ea reiciendis maiores. Eaque ab quod possimus obcaecati voluptates deserunt nihil quas vero optio. Libero voluptatem qui dicta necessitatibus? At doloremque iusto inventore, consequatur praesentium nisi similique ullam cum sapiente minus, officia error tempore, eum fugit a voluptate optio? Numquam, aut maxime. Quae, modi delectus!</p>
    </div>
  )
}